### ISSUE TITLE
如何在旧版本 Ubuntu 上运行？

### ISSUE THREAD

**Issue by UjuiUjuMandan** [james58899/hath-rust#186]
20.04 版本的 Ubuntu 运行从 Releases 下载的 hath-rust 时会报告什么版本的 glibc 找不到。只有更新到 22.04 才能用。

**Comment by james58899** [comment]
[v1.0.2](https://github.com/james58899/hath-rust/releases/tag/v1.0.2) 降低了 glibc 要求，現在可以在 ubuntu 20.04 上運行了。
