### ISSUE TITLE
在 macOS 上运行时如何忽略系统代理？

### ISSUE THREAD

**Issue by UjuiUjuMandan** [james58899/hath-rust#215]
我看到程序有 `--proxy` 参数，但是我需要覆盖系统代理到没有代理，请问如何操作呢？

**Comment by james58899** [comment]
Fixed in https://github.com/james58899/hath-rust/commit/904d46cd08f9e69d3eb194fb818d1c656fe0ae8c

現在會忽略系統的設定，只能透過參數設定proxy。
