### ISSUE TITLE
关于Github Action编译

### ISSUE THREAD

**Issue by taskmgr818** [james58899/hath-rust#244]
您好，我将本项目fork后仅对rust.yml进行了编辑（删除其中windows及MAC的部分），并尝试使用Github Action进行编译，但[编译失败](https://github.com/taskmgr818/hath-rust/actions/runs/8219640209)。
![image](https://github.com/james58899/hath-rust/assets/124493597/5aa1c5dd-1eec-4063-afa9-4fdfc7d416f0)
我对rust并不熟悉，无法确定问题发生的原因，您对此有头绪吗

另：我对dev分支下armv7的二进制文件进行了测试，可以正常运行（不过尚未在生产环境下进行长时间的测试）

**Comment by james58899** [comment]
rust nighlty 改了一些東西導致這一段無法編譯，具體來說是因為 `warn!()` 裡面包含了 `await` 導致的。
https://github.com/james58899/hath-rust/blob/8c435784b3343c1a2c10b78e3b729b35983be27b/src/rpc.rs#L493-L497

目前已經在main上修正，以及dev上的armv7相關變更也已經cherry-pick到main。

**Comment by taskmgr818** [comment]
感谢！
