### ISSUE TITLE
Hangs on Build

### ISSUE THREAD

**Issue by Yui907** [james58899/hath-rust#342]
Upon giving the command
/cargo build --release
Building will progress as normal until step 352, where it will hang forever.
This is the 'building' stage hath-rust(bin).

This is running on an RPI 3B+

Is there any way to resolve this?
What info can I provide you?

**Comment by james58899** [comment]
The last step usually takes a long time, so it's not stuck, it's just running.

You can download the binary built by CI directly from [Release](https://github.com/james58899/hath-rust/releases/latest), the **aarch64-unknown-linux** variant should suit you.
